### ISSUE TITLE
Missing specific tag version on dockerhub images

### ISSUE THREAD

**Issue by mtparet** [neuvector/prometheus-exporter#12]
Only a moving latest tag is available for now, could you make a versionned tag ?

It should the the last need to switch to neuvector repository https://github.com/neuvector/neuvector-helm/pull/31/files#diff-ba05023d0f1b5d4b64b6cad4cf9a7ecdR98

**Comment by becitsthere** [comment]
0.9.0 tag has been created for both github and container images in the dockerhub.
